[build]
  command = "npm run build"
  publish = "out"
  functions = ".netlify/functions"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18.18.0"
  NPM_FLAGS = "--legacy-peer-deps --force"

# Netlify DB Configuration (Powered by Neon)
[[databases]]
  name = "usd-financial-db"
  engine = "neon"
  region = "us-east-1"
  
[context.production.environment]
  NODE_ENV = "production"
  NODE_VERSION = "18.18.0"
  DATABASE_URL = "${NEON_DATABASE_URL}"
  DIRECT_URL = "${NEON_DIRECT_URL}"
  
[context.deploy-preview.environment]
  NODE_ENV = "preview"
  NODE_VERSION = "18.18.0"
  DATABASE_URL = "${NEON_DATABASE_URL}"
  DIRECT_URL = "${NEON_DIRECT_URL}"
  
[context.branch-deploy.environment]
  NODE_ENV = "development"
  NODE_VERSION = "18.18.0"

# Handle client-side routing with Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
# Enable pretty URLs by default
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Handle Next.js static files
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Referrer-Policy = "strict-origin-when-cross-origin"